// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.0-alpha1-19576-01")]
    public sealed partial class md52 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(md52));
        
        string IMigrationMetadata.Id
        {
            get { return "201911290022536_md52"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
