// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class md_createshippingorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(md_createshippingorder));
        
        string IMigrationMetadata.Id
        {
            get { return "202003100138247_md_createshippingorder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
