// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_ReceiptQty_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_ReceiptQty_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "202105081301472_add_ReceiptQty_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
